apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eventified-frontend-ingress
  namespace: eventified
spec:
  rules:
    - host: cloud.kosickaakademia.sk
      http:
        paths:
          - path: /eventified
            pathType: Prefix
            backend:
              service:
                name: eventified-frontend-service
                port:
                  number: 80
          