apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eventified-ingress
  namespace: eventified
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: eventified-strip-prefix-eventified@kubernetescrd
spec:
  rules:
    - host: cloud.kosickaakademia.sk  
      http:
        paths:
          # Backend API routes
          - path: /eventified/api
            pathType: Prefix
            backend:
              service:
                name: eventified-backend-service
                port:
                  number: 8080
          # Frontend routes
          - path: /eventified
            pathType: Prefix
            backend:
              service:
                name: eventified-frontend-service
                port:
                  number: 80
          