apiVersion: v1
kind: Service
metadata:
  name: eventified-frontend-service
  namespace: eventified
spec:
  selector:
    app: eventified-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP